#!/bin/sh
# TODO: map caps lock to ctrl
# TODO: reduce motion blur
# TODO: keybinds for mission control pane 1234 -> option+1234

if ! command -v brew > /dev/null; then
  /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew update --force # https://github.com/Homebrew/brew/issues/1151

brew bundle --file=- <<EOF
  brew "ripgrep"
  brew "fzf"
  brew "neovim"
  brew "tree-sitter-cli"
  brew "zsh"
  brew "tmux"
  cask "alacritty"

  brew "koekeishiya/formulae/skhd"
  brew "koekeishiya/formulae/yabai"

  cask "discord"
  cask "zen"

  brew "gh"

  brew "postgres", restart_service: :changed
  brew "redis", restart_service: :changed

  brew "crystal"
  tap "luckyframework/homebrew-lucky"
  brew "lucky"
  brew "yarn"
  brew "mise"

  brew "colima"
  brew "docker"
  brew "docker-compose"
  brew "docker-credential-helper"
EOF


if [ ! -d ~/.oh-my-zsh ]; then
  git clone git@github.com:robbyrussell/oh-my-zsh.git ~/.oh-my-zsh || git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

eval "$(mise activate bash)"

install_mise_language() {
  local language="$1"
  mise use --global "$language@latest"
}

install_mise_language "ruby"
eval "$(mise activate bash)"
gem update --system
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

install_mise_language "node"
