selection:
  save_to_clipboard: true

font:
  normal:
    family: JetBrainsMono Nerd Font

window:
  opacity: 0.98
  decorations: none

colors:
  primary:
    background: '0x22212c'
    foreground: '0xf8f8f2'

  normal:
    black:   '0x454158'
    red:     '0xff9580'
    green:   '0x8aff80'
    yellow:  '0xffff80'
    blue:    '0x9580ff'
    magenta: '0xff80bf'
    cyan:    '0x80ffea'
    white:   '0xf8f8f2'

  bright:
    black:   '0x504c67'
    red:     '0xffaa99'
    green:   '0xa2ff99'
    yellow:  '0xffff99'
    blue:    '0xaa99ff'
    magenta: '0xff99cc'
    cyan:    '0x99ffee'
    white:   '0xffffff'
