#!/usr/bin/env bash

set -e

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if command -v apt > /dev/null && [ -f /etc/lsb-release ]; then
  "$SCRIPT_DIR"/apt/install
  . $HOME/.asdf/asdf.sh
fi

if command -v pacman; then
  "$SCRIPT_DIR"/pacman/install
  . /opt/asdf-vm/asdf.sh
fi

if [[ $OSTYPE == 'darwin'* ]]; then
  "$SCRIPT_DIR"/brew/install
fi

$SCRIPT_DIR/link-dotfiles.rb
