#! /usr/bin/env bash

set -e

if ! command -v mise > /dev/null; then
  curl https://mise.run | sh
fi

export PATH="$HOME/.local/bin:$PATH"
eval "$(mise activate bash)"

mise use --global ruby@latest
mise use --global node@latest
