#!/bin/bash

set -e

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

sudo pacman -Syy

if ! command -v yay &> /dev/null
then
  echo "Installing yay"
  sudo pacman -S --noconfirm --needed git base-devel
  tmp_dir=$(mktemp -d)
  git clone https://aur.archlinux.org/yay.git $tmp_dir
  cd $tmp_dir
  makepkg -si --noconfirm
fi

cat "$SCRIPT_DIR"/pkglist.txt | xargs yay -S --needed --noconfirm

# asdf
. /opt/asdf-vm/asdf.sh
asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git || true
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git || true

latest_ruby=$(asdf list-all ruby | ag "^[2-9].[0-9].[0-9]$" | tail -1)

asdf install ruby $latest_ruby
asdf global ruby $latest_ruby
