#!/bin/bash

i3-msg "workspace 2; append_layout /home/alex/.dotfiles/.i3/layouts/single-urxvt-pane.json"
urxvt &
i3-msg "workspace 3; append_layout /home/alex/.dotfiles/.i3/layouts/single-google-chrome-pane.json"
google-chrome --new-window 'https://github.com/pachonk' &
i3-msg "workspace 4; append_layout /home/alex/.dotfiles/.i3/layouts/chat.json"
slack &
discord &
sleep 2 # wait for chrome to start, after it's started other windows start faster
i3-msg "workspace 1; append_layout /home/alex/.dotfiles/.i3/layouts/media.json"
google-chrome --new-window 'https://www.netflix.com/' 'https://www.hulu.com/' &
