#!/usr/bin/env bash

set -e

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if command -v apt; then
  "$SCRIPT_DIR"/apt/install
  . $HOME/.asdf/asdf.sh
fi

if [ -f /etc/arch-release ]; then
  "$SCRIPT_DIR"/arch/install
  . /opt/asdf-vm/asdf.sh
fi

$SCRIPT_DIR/link-dotfiles.rb
