name: Push Docker Image to grepsedawk/dotfiles
on:
  push:
    branches:
      - main

jobs:
  arch-dotfile-docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: grepsedawk/dotfiles
          flavor: |
            latest=true

      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.arch
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
