name: Run Install Script
on: [push]
jobs:
  apt-install-script-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./install


  arch-docker-install-script-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -f Dockerfile.arch .

  arch-full-install-script-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -f Dockerfile.arch-full .
